#############################################################################
# Makefile for building: ValpineBase
# Generated by qmake (3.0) (Qt 5.4.1)
# Project:  ValpineBase.pro
# Template: subdirs
# Command: C:\Qt\5.4\mingw491_32\bin\qmake.exe -spec win32-g++ CONFIG+=debug -o Makefile ValpineBase.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = C:\Qt\5.4\mingw491_32\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = copy /y
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-IDE-Library \
		sub-IDE-External \
		sub-IDE-Tests


sub-IDE-Library-qmake_all:  FORCE
	@if not exist IDE\Library\ mkdir IDE\Library\ & if not exist IDE\Library\ exit 1
	cd IDE\Library\ && $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\Library\Library.pro -spec win32-g++ CONFIG+=debug -o Makefile
	cd IDE\Library\ && $(MAKE) -f Makefile qmake_all
sub-IDE-Library: FORCE
	@if not exist IDE\Library\ mkdir IDE\Library\ & if not exist IDE\Library\ exit 1
	cd IDE\Library\ && ( if not exist Makefile $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\Library\Library.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-IDE-Library-make_first-ordered: FORCE
	@if not exist IDE\Library\ mkdir IDE\Library\ & if not exist IDE\Library\ exit 1
	cd IDE\Library\ && ( if not exist Makefile $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\Library\Library.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-IDE-Library-make_first: FORCE
	@if not exist IDE\Library\ mkdir IDE\Library\ & if not exist IDE\Library\ exit 1
	cd IDE\Library\ && ( if not exist Makefile $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\Library\Library.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-IDE-Library-all-ordered: FORCE
	@if not exist IDE\Library\ mkdir IDE\Library\ & if not exist IDE\Library\ exit 1
	cd IDE\Library\ && ( if not exist Makefile $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\Library\Library.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-IDE-Library-all: FORCE
	@if not exist IDE\Library\ mkdir IDE\Library\ & if not exist IDE\Library\ exit 1
	cd IDE\Library\ && ( if not exist Makefile $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\Library\Library.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-IDE-Library-clean-ordered: FORCE
	@if not exist IDE\Library\ mkdir IDE\Library\ & if not exist IDE\Library\ exit 1
	cd IDE\Library\ && ( if not exist Makefile $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\Library\Library.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-IDE-Library-clean: FORCE
	@if not exist IDE\Library\ mkdir IDE\Library\ & if not exist IDE\Library\ exit 1
	cd IDE\Library\ && ( if not exist Makefile $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\Library\Library.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-IDE-Library-distclean-ordered: FORCE
	@if not exist IDE\Library\ mkdir IDE\Library\ & if not exist IDE\Library\ exit 1
	cd IDE\Library\ && ( if not exist Makefile $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\Library\Library.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-IDE-Library-distclean: FORCE
	@if not exist IDE\Library\ mkdir IDE\Library\ & if not exist IDE\Library\ exit 1
	cd IDE\Library\ && ( if not exist Makefile $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\Library\Library.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-IDE-Library-install_subtargets-ordered: FORCE
	@if not exist IDE\Library\ mkdir IDE\Library\ & if not exist IDE\Library\ exit 1
	cd IDE\Library\ && ( if not exist Makefile $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\Library\Library.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-IDE-Library-install_subtargets: FORCE
	@if not exist IDE\Library\ mkdir IDE\Library\ & if not exist IDE\Library\ exit 1
	cd IDE\Library\ && ( if not exist Makefile $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\Library\Library.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-IDE-Library-uninstall_subtargets-ordered: FORCE
	@if not exist IDE\Library\ mkdir IDE\Library\ & if not exist IDE\Library\ exit 1
	cd IDE\Library\ && ( if not exist Makefile $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\Library\Library.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-IDE-Library-uninstall_subtargets: FORCE
	@if not exist IDE\Library\ mkdir IDE\Library\ & if not exist IDE\Library\ exit 1
	cd IDE\Library\ && ( if not exist Makefile $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\Library\Library.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-IDE-External-qmake_all: sub-IDE-Library-qmake_all FORCE
	@if not exist IDE\External\ mkdir IDE\External\ & if not exist IDE\External\ exit 1
	cd IDE\External\ && $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\External\External.pro -spec win32-g++ CONFIG+=debug -o Makefile
	cd IDE\External\ && $(MAKE) -f Makefile qmake_all
sub-IDE-External: FORCE
	@if not exist IDE\External\ mkdir IDE\External\ & if not exist IDE\External\ exit 1
	cd IDE\External\ && ( if not exist Makefile $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\External\External.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-IDE-External-make_first-ordered: sub-IDE-Library-make_first-ordered  FORCE
	@if not exist IDE\External\ mkdir IDE\External\ & if not exist IDE\External\ exit 1
	cd IDE\External\ && ( if not exist Makefile $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\External\External.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-IDE-External-make_first: FORCE
	@if not exist IDE\External\ mkdir IDE\External\ & if not exist IDE\External\ exit 1
	cd IDE\External\ && ( if not exist Makefile $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\External\External.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-IDE-External-all-ordered: sub-IDE-Library-all-ordered  FORCE
	@if not exist IDE\External\ mkdir IDE\External\ & if not exist IDE\External\ exit 1
	cd IDE\External\ && ( if not exist Makefile $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\External\External.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-IDE-External-all: FORCE
	@if not exist IDE\External\ mkdir IDE\External\ & if not exist IDE\External\ exit 1
	cd IDE\External\ && ( if not exist Makefile $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\External\External.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-IDE-External-clean-ordered: sub-IDE-Library-clean-ordered  FORCE
	@if not exist IDE\External\ mkdir IDE\External\ & if not exist IDE\External\ exit 1
	cd IDE\External\ && ( if not exist Makefile $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\External\External.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-IDE-External-clean: FORCE
	@if not exist IDE\External\ mkdir IDE\External\ & if not exist IDE\External\ exit 1
	cd IDE\External\ && ( if not exist Makefile $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\External\External.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-IDE-External-distclean-ordered: sub-IDE-Library-distclean-ordered  FORCE
	@if not exist IDE\External\ mkdir IDE\External\ & if not exist IDE\External\ exit 1
	cd IDE\External\ && ( if not exist Makefile $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\External\External.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-IDE-External-distclean: FORCE
	@if not exist IDE\External\ mkdir IDE\External\ & if not exist IDE\External\ exit 1
	cd IDE\External\ && ( if not exist Makefile $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\External\External.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-IDE-External-install_subtargets-ordered: sub-IDE-Library-install_subtargets-ordered  FORCE
	@if not exist IDE\External\ mkdir IDE\External\ & if not exist IDE\External\ exit 1
	cd IDE\External\ && ( if not exist Makefile $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\External\External.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-IDE-External-install_subtargets: FORCE
	@if not exist IDE\External\ mkdir IDE\External\ & if not exist IDE\External\ exit 1
	cd IDE\External\ && ( if not exist Makefile $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\External\External.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-IDE-External-uninstall_subtargets-ordered: sub-IDE-Library-uninstall_subtargets-ordered  FORCE
	@if not exist IDE\External\ mkdir IDE\External\ & if not exist IDE\External\ exit 1
	cd IDE\External\ && ( if not exist Makefile $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\External\External.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-IDE-External-uninstall_subtargets: FORCE
	@if not exist IDE\External\ mkdir IDE\External\ & if not exist IDE\External\ exit 1
	cd IDE\External\ && ( if not exist Makefile $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\External\External.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-IDE-Tests-qmake_all: sub-IDE-External-qmake_all FORCE
	@if not exist IDE\Tests\ mkdir IDE\Tests\ & if not exist IDE\Tests\ exit 1
	cd IDE\Tests\ && $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\Tests\Tests.pro -spec win32-g++ CONFIG+=debug -o Makefile
	cd IDE\Tests\ && $(MAKE) -f Makefile qmake_all
sub-IDE-Tests: FORCE
	@if not exist IDE\Tests\ mkdir IDE\Tests\ & if not exist IDE\Tests\ exit 1
	cd IDE\Tests\ && ( if not exist Makefile $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\Tests\Tests.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-IDE-Tests-make_first-ordered: sub-IDE-External-make_first-ordered  FORCE
	@if not exist IDE\Tests\ mkdir IDE\Tests\ & if not exist IDE\Tests\ exit 1
	cd IDE\Tests\ && ( if not exist Makefile $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\Tests\Tests.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-IDE-Tests-make_first: FORCE
	@if not exist IDE\Tests\ mkdir IDE\Tests\ & if not exist IDE\Tests\ exit 1
	cd IDE\Tests\ && ( if not exist Makefile $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\Tests\Tests.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-IDE-Tests-all-ordered: sub-IDE-External-all-ordered  FORCE
	@if not exist IDE\Tests\ mkdir IDE\Tests\ & if not exist IDE\Tests\ exit 1
	cd IDE\Tests\ && ( if not exist Makefile $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\Tests\Tests.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-IDE-Tests-all: FORCE
	@if not exist IDE\Tests\ mkdir IDE\Tests\ & if not exist IDE\Tests\ exit 1
	cd IDE\Tests\ && ( if not exist Makefile $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\Tests\Tests.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-IDE-Tests-clean-ordered: sub-IDE-External-clean-ordered  FORCE
	@if not exist IDE\Tests\ mkdir IDE\Tests\ & if not exist IDE\Tests\ exit 1
	cd IDE\Tests\ && ( if not exist Makefile $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\Tests\Tests.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-IDE-Tests-clean: FORCE
	@if not exist IDE\Tests\ mkdir IDE\Tests\ & if not exist IDE\Tests\ exit 1
	cd IDE\Tests\ && ( if not exist Makefile $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\Tests\Tests.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-IDE-Tests-distclean-ordered: sub-IDE-External-distclean-ordered  FORCE
	@if not exist IDE\Tests\ mkdir IDE\Tests\ & if not exist IDE\Tests\ exit 1
	cd IDE\Tests\ && ( if not exist Makefile $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\Tests\Tests.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-IDE-Tests-distclean: FORCE
	@if not exist IDE\Tests\ mkdir IDE\Tests\ & if not exist IDE\Tests\ exit 1
	cd IDE\Tests\ && ( if not exist Makefile $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\Tests\Tests.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-IDE-Tests-install_subtargets-ordered: sub-IDE-External-install_subtargets-ordered  FORCE
	@if not exist IDE\Tests\ mkdir IDE\Tests\ & if not exist IDE\Tests\ exit 1
	cd IDE\Tests\ && ( if not exist Makefile $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\Tests\Tests.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-IDE-Tests-install_subtargets: FORCE
	@if not exist IDE\Tests\ mkdir IDE\Tests\ & if not exist IDE\Tests\ exit 1
	cd IDE\Tests\ && ( if not exist Makefile $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\Tests\Tests.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-IDE-Tests-uninstall_subtargets-ordered: sub-IDE-External-uninstall_subtargets-ordered  FORCE
	@if not exist IDE\Tests\ mkdir IDE\Tests\ & if not exist IDE\Tests\ exit 1
	cd IDE\Tests\ && ( if not exist Makefile $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\Tests\Tests.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-IDE-Tests-uninstall_subtargets: FORCE
	@if not exist IDE\Tests\ mkdir IDE\Tests\ & if not exist IDE\Tests\ exit 1
	cd IDE\Tests\ && ( if not exist Makefile $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\Tests\Tests.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: ValpineBase.pro C:/Qt/5.4/mingw491_32/mkspecs/win32-g++/qmake.conf C:/Qt/5.4/mingw491_32/mkspecs/features/spec_pre.prf \
		C:/Qt/5.4/mingw491_32/mkspecs/qdevice.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/features/device_config.prf \
		C:/Qt/5.4/mingw491_32/mkspecs/common/shell-win32.conf \
		C:/Qt/5.4/mingw491_32/mkspecs/qconfig.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_axbase.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_axbase_private.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_axcontainer.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_axcontainer_private.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_axserver.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_axserver_private.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_bluetooth.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_bluetooth_private.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_bootstrap_private.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_clucene_private.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_concurrent.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_concurrent_private.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_core.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_core_private.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_dbus.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_dbus_private.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_declarative.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_declarative_private.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_designer.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_designer_private.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_designercomponents_private.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_enginio.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_enginio_private.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_gui.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_gui_private.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_help.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_help_private.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_location.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_location_private.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_multimedia.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_multimedia_private.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_multimediawidgets.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_network.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_network_private.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_nfc.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_nfc_private.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_opengl.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_opengl_private.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_openglextensions.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_openglextensions_private.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_platformsupport_private.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_positioning.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_positioning_private.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_printsupport.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_printsupport_private.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_qml.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_qml_private.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_qmltest.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_qmltest_private.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_quick.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_quick_private.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_quickparticles_private.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_quickwidgets.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_script.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_script_private.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_scripttools.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_scripttools_private.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_sensors.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_sensors_private.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_serialport.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_serialport_private.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_sql.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_sql_private.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_svg.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_svg_private.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_testlib.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_testlib_private.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_uitools.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_uitools_private.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_webchannel.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_webchannel_private.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_webkit.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_webkit_private.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_webkitwidgets.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_websockets.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_websockets_private.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_widgets.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_widgets_private.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_winextras.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_winextras_private.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_xml.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_xml_private.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_xmlpatterns.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		C:/Qt/5.4/mingw491_32/mkspecs/features/qt_functions.prf \
		C:/Qt/5.4/mingw491_32/mkspecs/features/qt_config.prf \
		C:/Qt/5.4/mingw491_32/mkspecs/features/win32/qt_config.prf \
		C:/Qt/5.4/mingw491_32/mkspecs/win32-g++/qmake.conf \
		C:/Qt/5.4/mingw491_32/mkspecs/features/spec_post.prf \
		C:/Qt/5.4/mingw491_32/mkspecs/features/exclusive_builds.prf \
		C:/Qt/5.4/mingw491_32/mkspecs/features/default_pre.prf \
		C:/Qt/5.4/mingw491_32/mkspecs/features/win32/default_pre.prf \
		C:/Qt/5.4/mingw491_32/mkspecs/features/resolve_config.prf \
		C:/Qt/5.4/mingw491_32/mkspecs/features/exclusive_builds_post.prf \
		C:/Qt/5.4/mingw491_32/mkspecs/features/default_post.prf \
		C:/Qt/5.4/mingw491_32/mkspecs/features/win32/rtti.prf \
		C:/Qt/5.4/mingw491_32/mkspecs/features/precompile_header.prf \
		C:/Qt/5.4/mingw491_32/mkspecs/features/warn_on.prf \
		C:/Qt/5.4/mingw491_32/mkspecs/features/win32/windows.prf \
		C:/Qt/5.4/mingw491_32/mkspecs/features/testcase_targets.prf \
		C:/Qt/5.4/mingw491_32/mkspecs/features/exceptions.prf \
		C:/Qt/5.4/mingw491_32/mkspecs/features/yacc.prf \
		C:/Qt/5.4/mingw491_32/mkspecs/features/lex.prf \
		ValpineBase.pro
	$(QMAKE) -spec win32-g++ CONFIG+=debug -o Makefile ValpineBase.pro
C:\Qt\5.4\mingw491_32\mkspecs\features\spec_pre.prf:
C:\Qt\5.4\mingw491_32\mkspecs\qdevice.pri:
C:\Qt\5.4\mingw491_32\mkspecs\features\device_config.prf:
C:\Qt\5.4\mingw491_32\mkspecs\common\shell-win32.conf:
C:\Qt\5.4\mingw491_32\mkspecs\qconfig.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_axbase.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_axbase_private.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_axcontainer.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_axcontainer_private.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_axserver.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_axserver_private.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_bluetooth.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_bluetooth_private.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_bootstrap_private.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_clucene_private.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_concurrent.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_concurrent_private.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_core.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_core_private.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_dbus.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_dbus_private.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_declarative.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_declarative_private.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_designer.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_designer_private.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_designercomponents_private.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_enginio.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_enginio_private.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_gui.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_gui_private.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_help.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_help_private.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_location.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_location_private.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_multimedia.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_multimedia_private.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_multimediawidgets.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_network.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_network_private.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_nfc.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_nfc_private.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_opengl.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_opengl_private.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_openglextensions.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_openglextensions_private.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_platformsupport_private.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_positioning.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_positioning_private.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_printsupport.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_printsupport_private.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_qml.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_qml_private.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_qmldevtools_private.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_qmltest.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_qmltest_private.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_quick.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_quick_private.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_quickparticles_private.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_quickwidgets.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_quickwidgets_private.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_script.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_script_private.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_scripttools.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_scripttools_private.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_sensors.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_sensors_private.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_serialport.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_serialport_private.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_sql.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_sql_private.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_svg.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_svg_private.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_testlib.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_testlib_private.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_uitools.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_uitools_private.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_webchannel.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_webchannel_private.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_webkit.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_webkit_private.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_webkitwidgets.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_webkitwidgets_private.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_websockets.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_websockets_private.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_widgets.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_widgets_private.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_winextras.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_winextras_private.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_xml.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_xml_private.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_xmlpatterns.pri:
C:\Qt\5.4\mingw491_32\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
C:\Qt\5.4\mingw491_32\mkspecs\features\qt_functions.prf:
C:\Qt\5.4\mingw491_32\mkspecs\features\qt_config.prf:
C:\Qt\5.4\mingw491_32\mkspecs\features\win32\qt_config.prf:
C:\Qt\5.4\mingw491_32\mkspecs\win32-g++\qmake.conf:
C:\Qt\5.4\mingw491_32\mkspecs\features\spec_post.prf:
C:\Qt\5.4\mingw491_32\mkspecs\features\exclusive_builds.prf:
C:\Qt\5.4\mingw491_32\mkspecs\features\default_pre.prf:
C:\Qt\5.4\mingw491_32\mkspecs\features\win32\default_pre.prf:
C:\Qt\5.4\mingw491_32\mkspecs\features\resolve_config.prf:
C:\Qt\5.4\mingw491_32\mkspecs\features\exclusive_builds_post.prf:
C:\Qt\5.4\mingw491_32\mkspecs\features\default_post.prf:
C:\Qt\5.4\mingw491_32\mkspecs\features\win32\rtti.prf:
C:\Qt\5.4\mingw491_32\mkspecs\features\precompile_header.prf:
C:\Qt\5.4\mingw491_32\mkspecs\features\warn_on.prf:
C:\Qt\5.4\mingw491_32\mkspecs\features\win32\windows.prf:
C:\Qt\5.4\mingw491_32\mkspecs\features\testcase_targets.prf:
C:\Qt\5.4\mingw491_32\mkspecs\features\exceptions.prf:
C:\Qt\5.4\mingw491_32\mkspecs\features\yacc.prf:
C:\Qt\5.4\mingw491_32\mkspecs\features\lex.prf:
ValpineBase.pro:
qmake: FORCE
	@$(QMAKE) -spec win32-g++ CONFIG+=debug -o Makefile ValpineBase.pro

qmake_all: sub-IDE-Library-qmake_all sub-IDE-External-qmake_all sub-IDE-Tests-qmake_all FORCE

make_first: sub-IDE-Library-make_first-ordered sub-IDE-External-make_first-ordered sub-IDE-Tests-make_first-ordered FORCE
all: sub-IDE-Library-all-ordered sub-IDE-External-all-ordered sub-IDE-Tests-all-ordered FORCE
clean: sub-IDE-Library-clean-ordered sub-IDE-External-clean-ordered sub-IDE-Tests-clean-ordered FORCE
distclean: sub-IDE-Library-distclean-ordered sub-IDE-External-distclean-ordered sub-IDE-Tests-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-IDE-Library-install_subtargets-ordered sub-IDE-External-install_subtargets-ordered sub-IDE-Tests-install_subtargets-ordered FORCE
uninstall_subtargets: sub-IDE-Library-uninstall_subtargets-ordered sub-IDE-External-uninstall_subtargets-ordered sub-IDE-Tests-uninstall_subtargets-ordered FORCE

sub-IDE-Library-debug_ordered:
	@if not exist IDE\Library\ mkdir IDE\Library\ & if not exist IDE\Library\ exit 1
	cd IDE\Library\ && ( if not exist Makefile $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\Library\Library.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile debug
sub-IDE-External-debug_ordered: sub-IDE-Library-debug_ordered 
	@if not exist IDE\External\ mkdir IDE\External\ & if not exist IDE\External\ exit 1
	cd IDE\External\ && ( if not exist Makefile $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\External\External.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile debug
sub-IDE-Tests-debug_ordered: sub-IDE-External-debug_ordered 
	@if not exist IDE\Tests\ mkdir IDE\Tests\ & if not exist IDE\Tests\ exit 1
	cd IDE\Tests\ && ( if not exist Makefile $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\Tests\Tests.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile debug
debug: sub-IDE-Library-debug_ordered sub-IDE-External-debug_ordered sub-IDE-Tests-debug_ordered

sub-IDE-Library-release_ordered:
	@if not exist IDE\Library\ mkdir IDE\Library\ & if not exist IDE\Library\ exit 1
	cd IDE\Library\ && ( if not exist Makefile $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\Library\Library.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile release
sub-IDE-External-release_ordered: sub-IDE-Library-release_ordered 
	@if not exist IDE\External\ mkdir IDE\External\ & if not exist IDE\External\ exit 1
	cd IDE\External\ && ( if not exist Makefile $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\External\External.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile release
sub-IDE-Tests-release_ordered: sub-IDE-External-release_ordered 
	@if not exist IDE\Tests\ mkdir IDE\Tests\ & if not exist IDE\Tests\ exit 1
	cd IDE\Tests\ && ( if not exist Makefile $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\Tests\Tests.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile release
release: sub-IDE-Library-release_ordered sub-IDE-External-release_ordered sub-IDE-Tests-release_ordered

sub-IDE-Library-check_ordered:
	@if not exist IDE\Library\ mkdir IDE\Library\ & if not exist IDE\Library\ exit 1
	cd IDE\Library\ && ( if not exist Makefile $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\Library\Library.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
sub-IDE-External-check_ordered: sub-IDE-Library-check_ordered 
	@if not exist IDE\External\ mkdir IDE\External\ & if not exist IDE\External\ exit 1
	cd IDE\External\ && ( if not exist Makefile $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\External\External.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
sub-IDE-Tests-check_ordered: sub-IDE-External-check_ordered 
	@if not exist IDE\Tests\ mkdir IDE\Tests\ & if not exist IDE\Tests\ exit 1
	cd IDE\Tests\ && ( if not exist Makefile $(QMAKE) C:\Users\Dan\Dropbox\Dev\Valpineware\ValpineBase\IDE\Tests\Tests.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
check: sub-IDE-Library-check_ordered sub-IDE-External-check_ordered sub-IDE-Tests-check_ordered
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

